name: "CPI Testing"

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]


jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Pip install
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: CPI py test
        working-directory: src/
        run: python test.py

      - name: Compile c lib
        working-directory: src/cubiomespi/lib
        run: gcc -shared -o lib.dll -fPIC newlib.c cubiomes/util.c cubiomes/noise.c cubiomes/layers.c cubiomes/generator.c cubiomes/finders.c cubiomes/biometree.c cubiomes/biomenoise.c  -m64

